### ISSUE TITLE
support for running on a traditional linux distro (eg. debian?)

### ISSUE THREAD

**Issue by khimaros** [okcar-os/okcar#1]
i'd love to be able to stream content from my linux laptop or rpi4 running debian to a Carplay headunit. is this something that is feasible with okcar?

**Comment by leohuangyi** [comment]
This cannot be achieved in the short term, as many of our application layer tasks are developed based on the Android platform, such as video recording, audio collection, etc. Our team lacks experience in developing for traditional Linux distributions.
